name: fixed-tree
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - click
  - matplotlib
  - networkx
  - nextflow=23.04.1
  - numpy
  - treetime=0.11.4
  - pandoc
  - pip
  - python=3.10
  - pip:
      - treezy